language: python
python:
  - "3.5"
matrix:
  include:
  - env: TOX_ENV=flake8
  - env: TOX_ENV=py35
  - env: TOX_ENV=py36
    python: "3.6"
cache: pip
install:
  - "travis_retry pip install setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
