language: python
python:
  - "3.5"
matrix:
  include:
    - python: "3.5"
      env: TOX_ENV=py35
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "pypy3.5"
      env: TOX_ENV=pypy3
    - python: "3.5"
      env: TOX_ENV=flake8
cache:
  pip: true
install:
  - "travis_retry pip install setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
